### ISSUE TITLE
Unexpected token =

### ISSUE THREAD

**Issue by bufo24** [binance-exchange/node-binance-api#10]
I've got an error and I don't now how to solve it... can anyone help?
Here my output:

/home/pi/node-binance-api/node-binance-api.js:26
	const publicRequest = function(url, data, callback, method = "GET") {
	                                                           ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/pi/node-binance-api/examples/test.js:1:79)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)

**Comment by jaggedsoft** [comment]
Hi there, can you please check your node version with `node -v` and report back to me? Thank you :)
