### ISSUE TITLE
ENOTFOUND error when using in Firebase Cloud Function

### ISSUE THREAD

**Issue by evancaldwell** [binance-exchange/node-binance-api#103]
I'm trying to call `balance` and `openOrders` from a Firebase Cloud Function and getting an error:
```
{ Error: getaddrinfo ENOTFOUND api.binance.com api.binance.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'api.binance.com',
  host: 'api.binance.com',
  port: 443 }
```

Similar error for `balance`.
When I run it locally I get the data back that I would expect.

Inside of my cloud function it looks like:
```
exports.syncBalanceData = functions.https.onRequest((req, res) => {
  // sync balance data to firebase for evaluation
  binance.balance((error, balances) => {
    if (error) {
      console.log('balance error: ', error);
    } else {
      for (const index in balances) {
        if (balances.hasOwnProperty(index) && balances[index].available > 0.5) {
          const element = balances[index];
          console.log(index + ' balance: ', element.available);
        }
      }
    }
  });
});
```

**Comment by keith1024** [comment]
I'm not too familiar with the Firebase platform, but I believe you need to be on a paid plan to make external API calls. Either way, this is an issue you'll have to take up with Firebase.

**Comment by evancaldwell** [comment]
I didn't even think about that, thanks.
