### ISSUE TITLE
Sometime it's crashed while getting market depth

### ISSUE THREAD

**Issue by mrgoonie** [binance-exchange/node-binance-api#56]
Error below:

```
node_modules/node-binance-api/node-binance-api.js:315
                if ( typeof data.bids !== 'undefined' ) {
                                ^

TypeError: Cannot read property 'bids' of undefined
    at depthData (/Volumes/DATA/www/storm-alert/node_modules/node-binance-api/node-binance-api.js:315:19)
    at /Volumes/DATA/www/storm-alert/node_modules/node-binance-api/node-binance-api.js:497:39
    at Request._callback (/Volumes/DATA/www/storm-alert/node_modules/node-binance-api/node-binance-api.js:45:12)
    at self.callback (/Volumes/DATA/www/storm-alert/node_modules/request/request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/Volumes/DATA/www/storm-alert/node_modules/request/request.js:878:8)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
```

**Comment by jaggedsoft** [comment]
Thank you for this report, hopefully it will be fixed by the next release

**Comment by jaggedsoft** [comment]
Hopefully fixed here https://github.com/binance-exchange/node-binance-api/commit/c158f3f746bbfc4f65f2295f88bd4af10d7ba6d1

If not let me know thank you

**Comment by mrgoonie** [comment]
Nope, I've updated to 0.4.5 and it's still there...


```
/Volumes/DATA/www/storm-alert/node_modules/node-binance-api/node-binance-api.js:320
                if ( typeof data.bids !== 'undefined' ) {
                                ^

TypeError: Cannot read property 'bids' of undefined
    at depthData (/Volumes/DATA/www/storm-alert/node_modules/node-binance-api/node-binance-api.js:320:19)
    at /Volumes/DATA/www/storm-alert/node_modules/node-binance-api/node-binance-api.js:502:39
    at Request._callback (/Volumes/DATA/www/storm-alert/node_modules/node-binance-api/node-binance-api.js:45:12)
    at self.callback (/Volumes/DATA/www/storm-alert/node_modules/request/request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/Volumes/DATA/www/storm-alert/node_modules/request/request.js:878:8)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
```

**Comment by jaggedsoft** [comment]
you sure? that is no longer on line 320 in version `0.4.4`

![image](https://user-images.githubusercontent.com/4283360/35180468-db600266-fd65-11e7-84ac-d854cfc3d32b.png)

**Comment by mrgoonie** [comment]
Yea, my fault... sorry :)
